games/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hangman/', include('hangman.urls')),
]

hangman/urls.py
from django.urls import path
from . import views

app_name = 'hangman'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_game, name="new_game"),
    path('guess/', views.guess, name="guess"),
]

hangman/models.py
from django.db import models
from django.db.models.functions import Length

class WordManager(models.Manager):
    def length__gte(self, length):
        return self.annotate(word_len=Length('word')) \
            .filter(word_len__gte=length)

class Word(models.Model):
    word = models.TextField(max_length=40, unique=True)
    objects = WordManager()

    def __str__(self):
        return self.word

    def __repr__(self):
        return f"<Word: {self.word}>"

hangman/forms.py
from django import forms

def validate_guess(data):
    guess = str(data).strip()
    if len(guess) < 1:
        raise forms.ValidationError("Guess cannot be empty!")
    if not guess.isalpha():
        raise forms.ValidationError(
            "Guess must contain letters only!")


class GuessForm(forms.Form):
    guess = forms.CharField(max_length=20,
                            validators=[validate_guess])

    def __init__(self, *args, **kwargs):
        super(GuessForm, self).__init__(*args, **kwargs)
        self.fields['guess'].label = "Guess a letter or the word:"

hangman/views.py
from django.shortcuts import redirect, render, reverse
from django.contrib import messages
from hangman.hangman import Game
from .forms import GuessForm

def index(request):
    game_dict = request.session.get('game', None)
    game = Game(
        game_dict['word'],
        game_dict['guessed_letters'],
        game_dict['guesses']
    )
    print(game)
    game_dict['guessing_string'] = game.get_guessing_string()

    context = {
        'game': game_dict,
    }
    if not game.has_guessed_word:
        context['form'] = GuessForm()
    return render(request, 'index.html', context)

def new_game(request):
    game = Game()
    request.session['game'] = {
        'word': str(game.word),
        'guessed_letters': [],
        'guesses': 0,
    }
    return redirect(reverse('hangman:index'))

def guess(request):
    form = GuessForm(request.POST)
    if form.is_valid():
        guess = form.cleaned_data['guess']
        game_dict = request.session.get('game', None)
        game = Game(game_dict['word'], game_dict['guessed_letters'])
        if len(guess) == 1:
            valid_guess = game.guess_letter(guess)
        else:
            valid_guess = game.guess_word(guess)

        request.session['game'] = {
            'word': str(game.word),
            'guessed_letters': game.guessed_letters,
            'guesses': game.count_guesses,
            'has_guessed_word': game.has_guessed_word,
        }
    elif form.errors:
        for error in form.errors['guess']:
            messages.error(request, str(error))
    return redirect(reverse('hangman:index'))

hangman/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load render_bundle from webpack_loader %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <div id="content">
        {% render_bundle 'main' %}
        {% block content %}{% endblock %}
    </div>
    {% block javascript %}
    {% endblock %}
</body>
</html>

hangman/templates/index.html
{% extends 'base.html' %}
{% block title %}Djangman{% endblock %}
{% block content %}
<div class="text-center">
    <h1>Djangman</h1>
    <div class="container">
        {% if not game %}
            <p>You are not playing any games right now.</p>
            <p>Click below to start a new game.</p>
            <a href="{% url 'hangman:new_game' %}">New game</a>

        {% else %}
            <div>Current Game</div>
            <div>
                {% if not game.has_guessed_word %}
                    <pre>{{ game.guessing_string }}</pre>
                {% else %}
                    <a href="https://www.anagrammer.com/scrabble/{{ game.word }}"
                       target="_blank">
                        <pre>{{ game.guessing_string }} </pre>
                    </a>
                {% endif %}
            </div>
            <div>You have used <strong>{{ game.guesses }}</strong> guess{{ game.guesses|pluralize:"es" }}</div>
            {% for letter in game.guessed_letters %}
                <span class="badge badge-secondary">{{ letter }}</span>
            {% endfor %}
            <div>
                {% if not game.has_guessed_word %}
                    <form action="{% url 'hangman:guess' %}" method="post">
                        {{ form.as_table }}
                        <input type="submit" value="Guess">
                        {% csrf_token %}
                    </form>
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="error-message">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}

                {% else %}
                    <h3>Congratulations!<br> You have guessed the word!</h3>
                    <button onclick="location.href = '{% url 'hangman:new_game' %}'">New Game</button>
                {% endif %}
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}